import "./globals.css";

// ✅ You don't need Google fonts anymore
// import { Geist, Geist_Mono } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Preload background image manually */}
        <link
          rel="preload"
          as="image"
          href="https://mybarlow.barlowresearch.com/mybarlow/testdrive2025/images/backdrop.jpg"
        />

        {/* ✅ Futura font via local or fallback stack */}
        <style>{`
          @font-face {
            font-family: 'Futura';
            src: local('Futura'), url('/fonts/futura.woff2') format('woff2');
            font-display: swap;
          }
        `}</style>
      </head>
      <body style={{ fontFamily: "Futura, sans-serif" }}>{children}</body>
    </html>
  );
}
